"use client";

import { FormEvent, useEffect, useState } from "react";
import { RoleGate } from "@/components/AuthProvider";
import { api, DepartmentDashboard, Department, formatValue } from "@/lib/api";

export default function DepartmentsPage() {
  const [departments, setDepartments] = useState<Department[]>([]);
  const [details, setDetails] = useState<Record<string, DepartmentDashboard>>({});
  const [name, setName] = useState(""); const [showForm, setShowForm] = useState(false);
  const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  async function load() {
    setLoading(true);
    try { const rows=await api.departments(); setDepartments(rows); const data=await Promise.all(rows.map(d=>api.departmentDashboard(d.id).catch(()=>null))); const mapped:Record<string,DepartmentDashboard>={}; rows.forEach((d,i)=>{if(data[i])mapped[d.id]=data[i]!;}); setDetails(mapped); }
    catch(e){setError(e instanceof Error?e.message:"Could not load departments");} finally{setLoading(false);}
  }
  useEffect(()=>{void Promise.resolve().then(load);},[]);
  async function create(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError("");try{await api.createDepartment(name.trim());setName("");setShowForm(false);await load();}catch(e){setError(e instanceof Error?e.message:"Could not create department");}finally{setBusy(false);}}
  async function remove(dept:Department){if(!window.confirm(`Delete ${dept.name}? It must have no employees.`))return;setError("");try{await api.deleteDepartment(dept.id);await load();}catch(e){setError(e instanceof Error?e.message:"Could not delete department");}}

  return <RoleGate roles={["admin","manager"]}><div className="space-y-6">
    <div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><p className="text-xs font-semibold uppercase tracking-[0.14em] text-indigo-600">Organization</p><h1 className="mt-1 text-2xl font-semibold text-slate-900 sm:text-3xl">Departments</h1><p className="mt-2 text-sm text-slate-500">Create teams and compare AI adoption, time saved, and estimated ROI.</p></div><button onClick={()=>setShowForm(v=>!v)} className="w-fit rounded-xl bg-indigo-600 px-4 py-2.5 text-sm font-semibold text-white hover:bg-indigo-700">{showForm?"Close form":"+ Add department"}</button></div>
    {error&&<p role="alert" className="rounded-xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-800">{error.replace(/^API error \d+: /,"")}</p>}
    {showForm&&<form onSubmit={create} className="flex flex-col gap-3 rounded-2xl border border-indigo-100 bg-white p-5 shadow-sm sm:flex-row sm:items-end"><label className="flex-1 text-sm font-medium text-slate-700">Department name<input required maxLength={100} value={name} onChange={e=>setName(e.target.value)} placeholder="e.g. Customer Success" className="mt-1.5 w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm" /></label><button disabled={busy} className="rounded-xl bg-indigo-600 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-50">{busy?"Saving…":"Create department"}</button></form>}
    {loading?<div className="rounded-2xl border border-slate-200 bg-white p-12 text-center text-sm text-slate-400">Loading departments…</div>:<div className="grid grid-cols-1 gap-4 sm:grid-cols-2 xl:grid-cols-3">{departments.map(d=>{const stats=details[d.id];return <section key={d.id} className="overflow-hidden rounded-2xl border border-slate-200/80 bg-white shadow-sm"><div className="flex items-center gap-3 border-b border-slate-100 px-5 py-4"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-indigo-50 text-sm font-semibold text-indigo-700">{d.name.slice(0,1).toUpperCase()}</span><div className="min-w-0 flex-1"><h2 className="truncate font-semibold text-slate-900">{d.name}</h2><p className="text-xs text-slate-400">Team performance</p></div><button onClick={()=>void remove(d)} aria-label={`Delete ${d.name}`} className="rounded-lg p-2 text-slate-400 hover:bg-rose-50 hover:text-rose-600">×</button></div>{stats?<div className="p-5"><div className="grid grid-cols-2 gap-3"><div className="rounded-xl bg-slate-50 p-3"><p className="text-xs text-slate-500">Employees</p><p className="mt-1 text-lg font-semibold text-slate-900">{stats.employees}</p></div><div className="rounded-xl bg-slate-50 p-3"><p className="text-xs text-slate-500">Tasks</p><p className="mt-1 text-lg font-semibold text-slate-900">{stats.tasks}</p></div></div><div className="mt-5"><div className="flex justify-between text-xs"><span className="font-medium text-slate-600">AI adoption</span><span className="font-semibold text-indigo-700">{stats.ai_adoption_pct}%</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-gradient-to-r from-indigo-500 to-violet-500" style={{width:`${Math.max(0,Math.min(100,stats.ai_adoption_pct))}%`}}/></div></div><dl className="mt-5 space-y-3 border-t border-slate-100 pt-4 text-sm"><div className="flex justify-between"><dt className="text-slate-500">Time saved</dt><dd className="font-medium text-slate-800">{formatValue(stats.time_saved_minutes)} min</dd></div><div className="flex justify-between"><dt className="text-slate-500">AI spend</dt><dd className="font-medium text-slate-800">{formatValue(stats.ai_spend,"$")}</dd></div><div className="flex justify-between"><dt className="text-slate-500">Estimated ROI</dt><dd className="font-semibold text-slate-800">{typeof stats.roi_percentage==="number"?`${formatValue(stats.roi_percentage)}%`:stats.roi_percentage}</dd></div></dl></div>:<p className="p-5 text-sm text-slate-400">Team metrics are not available.</p>}</section>;})}{departments.length===0&&<div className="col-span-full rounded-2xl border border-dashed border-slate-300 bg-white px-6 py-14 text-center"><p className="font-medium text-slate-800">No departments yet</p><p className="mt-1 text-sm text-slate-500">Create a department to start organizing your team.</p></div>}</div>}
  </div></RoleGate>;
}
